 Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
    - "2.7"

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - pip install coveralls


install:
    - pip install -r requirements/test.txt

script:
    - flake8 document_clipper tests
    - coverage run --source document_clipper setup.py test

after_success:
    - coveralls
